const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../web/dashboard/app.js'),'utf8');
const settings=fs.readFileSync(path.join(__dirname,'../web/dashboard/settings.js'),'utf8');
function harness(storage={}) {
 const context=vm.createContext({URLSearchParams,console,crypto:require('node:crypto').webcrypto,window:{location:{origin:'https://stage.example'},addEventListener(){}},document:{addEventListener(){},getElementById:()=>null,querySelector:()=>null},navigator:{},sessionStorage:storage,localStorage:{getItem:()=>null},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0});
 Object.defineProperties(storage,{getItem:{value:key=>storage[key]||null,configurable:true},setItem:{value:(key,value)=>{storage[key]=value;},configurable:true},removeItem:{value:key=>{delete storage[key];},configurable:true}});
 vm.runInContext(settings,context);vm.runInContext(source.slice(0,source.lastIndexOf('(async () => {')),context);
 vm.runInContext(`el=(tag,attrs={},...children)=>({tag,attrs,children:children.flat(Infinity).filter(x=>x!=null&&x!==false)});render=()=>{};ibRegion=()=>{};toast=()=>{};staleNote=()=>{};loadInboxDetail=async()=>{};loadInbox=()=>{};state.user={id:'owner',role:'admin'};state.inbox.detail={grants:[]};`,context);
 return {context,storage,run:code=>vm.runInContext(code,context)};
}
const request={id:'rq_batch',agent_name:'Test agent',kind:'access',status:'pending',revision:1,expires_at:Date.now()+86400000,ttl_seconds:1800,tools:[{call_id:'alpha',tool:'files.write',required:true,summary:'Write alpha.',target:'alpha.txt',expected_effects:'A test file exists.',params:{path:{eq:'alpha.txt'}},flags:[]},{call_id:'beta',tool:'files.write',required:true,summary:'Write beta.',target:'beta.txt',expected_effects:'A second file exists.',params:{path:{eq:'beta.txt'}},flags:[]}]};
function setup(h){h.context.request=structuredClone(request);h.run('state.inbox.detail.request=request');}
function text(n){return typeof n==='object'&&n?(n.children||[]).map(text).join(' '):String(n||'');}
function nodes(n,tag){return typeof n==='object'&&n?[...(n.tag===tag?[n]:[]),...(n.children||[]).flatMap(c=>nodes(c,tag))]:[];}
function plain(x){return JSON.parse(JSON.stringify(x));}

test('checkboxes remain drafts and required rejection can submit a complete batch',()=>{const h=harness();setup(h);h.run('api=async()=>{throw new Error("checkbox must not send")};');let tree=h.run('ibDecideEl(request,[])');const ticks=nodes(tree,'button').filter(x=>x.attrs.role==='checkbox');ticks[0].attrs.on.click();tree=h.run('ibDecideEl(request,[])');assert.match(text(tree),/Accept 1, reject 1/);assert.doesNotMatch(text(tree),/Send back to agent/);const body=plain(h.run('ibApproveBody(request,state.inbox.allow[request.id])'));assert.deepEqual(body.verdicts,{alpha:{verdict:'rejected'},beta:{verdict:'accepted'}});assert.equal(body.request_revision,1);assert.ok(body.submission_id);assert.equal(body.action,'submit');});

test('all rejected stays enabled and sends no accepted verdict',()=>{const h=harness();setup(h);h.run('ibSelectCalls(request,[false,false])');const tree=h.run('ibDecideEl(request,[])');const submit=nodes(tree,'button').find(b=>text(b)==='Accept 0, reject 2');assert.ok(submit);assert.equal(submit.attrs.disabled,false);const body=plain(h.run('ibApproveBody(request,[false,false])'));assert.ok(Object.values(body.verdicts).every(x=>x.verdict==='rejected'));});

test('reasons and overall note survive navigation, reload and a new server revision',()=>{const h=harness();setup(h);let tree=h.run('ibDecideEl(request,[])');nodes(tree,'textarea').find(n=>n.attrs.id==='ib-call-reason-0').attrs.on.input({target:{value:'Reject this until the target is ready.'}});nodes(tree,'textarea').find(n=>n.attrs.id==='ib-call-reason-1').attrs.on.input({target:{value:'Accept this exact target.'}});nodes(tree,'textarea').find(n=>n.attrs.id==='ib-note').attrs.on.input({target:{value:'Keep both written reasons.'}});h.run('ibSelectCalls(request,[false,true])');const reloaded=harness(h.storage);setup(reloaded);reloaded.run('request.revision=2');tree=reloaded.run('ibDecideEl(request,[])');assert.match(text(tree),/server revision changed/);const body=plain(reloaded.run('ibApproveBody(request,state.inbox.allow[request.id])'));assert.equal(body.request_revision,1);assert.equal(body.note,'Keep both written reasons.');assert.equal(body.verdicts.alpha.reason,'Reject this until the target is ready.');assert.equal(body.verdicts.beta.reason,'Accept this exact target.');nodes(tree,'button').find(b=>text(b)==='Use reviewed revision').attrs.on.click();assert.equal(reloaded.run('ibApproveBody(request,state.inbox.allow[request.id]).request_revision'),2);});

test('failed or lost submissions preserve draft and retry key; changed content gets a new key',async()=>{const h=harness();setup(h);h.run('ibSelectCalls(request,[true,false]);api=async()=>{const e=new Error("offline");e.status=503;throw e;}');const first=plain(h.run('ibApproveBody(request,state.inbox.allow[request.id])'));h.context.body=first;await h.run('ibDecide(request,body)');const retry=plain(h.run('ibApproveBody(request,state.inbox.allow[request.id])'));assert.equal(retry.submission_id,first.submission_id);h.run('const draft=ibAccessDraft(request);draft.note="Changed note";ibSaveAccessDraft(request,draft)');assert.notEqual(h.run('ibApproveBody(request,state.inbox.allow[request.id]).submission_id'),first.submission_id);assert.ok(Object.keys(h.storage).some(k=>k.startsWith('toolyard.decision.')));});

test('user change isolates draft and logout removes user-specific data',()=>{const h=harness();setup(h);h.run('ibSelectCalls(request,[false,true])');h.run("state.user={id:'second',role:'member'}");assert.deepEqual(plain(h.run('ibAccessDraft(request).allow')),{alpha:true,beta:true});assert.equal(h.run("routeAllowed('inbox')"),true);h.run('ibSaveAccessDraft(request,ibAccessDraft(request));ibClearDrafts()');assert.ok(Object.keys(h.storage).every(k=>!k.startsWith('toolyard.decision.')));h.run("state.user={id:'owner',role:'admin'}");assert.deepEqual(plain(h.run('ibAccessDraft(request).allow')),{alpha:true,beta:true});assert.equal(h.run("workspaceRoute('approvals')"),'inbox');});

test('legacy decisions preserve original scope and omit grant lifetime controls',()=>{const h=harness();setup(h);h.run("request.execution_mode='legacy';state.inbox.ttl[request.id]=120;state.inbox.narrow[request.id]={0:{path:{eq:'other.txt'}}};ibAccessDraft(request);state.inbox.openParams[request.id+':alpha']=true;");const tree=h.run('ibDecideEl(request,[])');assert.match(text(tree),/Legacy execution/);assert.equal(nodes(tree,'select').length,0);assert.ok(!nodes(tree,'button').some(b=>text(b)==='Narrow'));const body=plain(h.run('ibApproveBody(request,[true,true])'));assert.equal(body.params,undefined);assert.equal(body.ttl_seconds,undefined);});

test('only failed callbacks expose an authorized retry control',async()=>{const h=harness();setup(h);h.run("state.inbox.detail.callbacks=[{event_id:'evt_failed',status:'failed',attempts:3,terminal_reason:'receiver offline',history:[{attempt:1,outcome:'timeout'}]},{event_id:'evt_delivered',status:'delivered',attempts:1}];let lastRequest;api=async(url,opts)=>{lastRequest={url,opts};};");const tree=h.run('ibDecideEl(request,[])');assert.match(text(tree),/receiver offline/);assert.match(text(tree),/Attempt 1 · timeout/);const retries=nodes(tree,'button').filter(b=>text(b)==='Retry callback');assert.equal(retries.length,1);await retries[0].attrs.on.click();assert.equal(h.run('lastRequest.url'),'/v1/inbox/rq_batch/callbacks/evt_failed/retry');});
